import { Hero } from './hero';

export const JUEGOS: Hero[] = [
  { id: 1, name: 'Left 4 Dead', description: 'El juego será de primera persona (FPS) y contará con modos single player y multiplayer (cooperativo) de 4 jugadores. El motoro gráfico del juego será el del Source, para algunos ya obsoletos por las sálida de juegos nuevos como Crysis, pero las físicas, fluidez y cantidad de enemigos que tendremos en pantalla nos harán olvidar la carga poligonal de los modelos.'},
  { id: 2, name: 'Grand Theft Auto V' , description: 'Nueve años después de un atraco frustrado en Ludendorff (North Yankton), que dejó a uno de sus perpetradores muerto, otro bajo arresto y obligó a un tercero a pasar a la clandestinidad, el ex ladrón de bancos, Michael Townley, fue dado por muerto en North Yankton y ha sido puesto bajo protección de testigos por el agente corrupto del FIB Dave Norton, amigo íntimo del mismo, trasladándolo así con su familia a Los Santos (San Andreas) con una nueva identidad: «Michael De Santa». A Franklin Clinton, que trabaja como embargador de vehículos en un concesionario de coches, junto con su amigo Lamar Davis, se le pide recuperar un vehículo perteneciente al hijo de Michael, Jimmy, quien está atrasado en el pago de su adquisición. Deduciendo que su hijo está punto de convertirse en una víctima de un fraude de crédito, Michael se esconde en el vehículo y se enfrenta a Franklin. Cuando éste conduce de camino al concesionario, lo obliga a estrellar el coche contra la vidriera del local. Clinton es despedido, pero él y De Santa se convierten en amigos.'  },
  { id: 3, name: 'Left 4 Dead 2' , description: 'Ambientado en el apocalipsis zombi, Left 4 Dead 2 (L4D2) es la secuela largamente esperada del galardonado Left 4 Dead, el juego co-op número 1 de 2008.Este FPS cooperativo de acción y horror os llevará a ti y a tus amigos por las ciudades, pantanos y cementerios del Sur Profundo, desde Savannah hasta Nueva Orleans a lo largo de cinco extensas campañas.'  },
  { id: 4, name: 'Battlefield 1' , description: 'Battlefield 1 supone el retorno a las raíces de esta veterana serie de videojuegos de acción bélica. El conflicto se traslada a los campos de batalla de la Primera Guerra Mundial, en los que podemos pilotar una amplia variedad de vehículos terrestres, marinos y aéreos; aparte de usar también un vasto arsenal de armas de fuego. Fidelidad histórica y espectacularidad son dos señas que han marcado el trabajo del equipo sueco de DICE, con una fiel recreación de armas, vehículos y escenarios, entre los que encontramos los Alpes italianos, los desiertos de Arabia o ciudades ubicadas en Francia. Battlefield 1 (antes conocido como Battlefield 5) ofrece una campaña para un solo jugador y el clásico multijugador para 64 personas.'  },
  { id: 5, name: 'Dark Souls' , description: 'Dark Souls es el nuevo juego de rol y acción de los creadores de Demons Souls, FromSoftware. Dark Souls cuenta con muchos elementos ya conocidos: un universo fantástico y oscuro, tortuosos recorridos por mazmorras, temibles enemigos e interacciones online exclusivas.' ,  },
  { id: 6, name: 'Uncharted 4' , description: 'En una experiencia ofrecida por la galardonada desarrolladora Naughty Dog, UNCHARTED: Colección Legado de los Ladrones incluye UNCHARTED™ 4: El desenlace del ladrón y UNCHARTED™: El legado perdido, dos aventuras para un jugador aclamadas por la crítica en las que recorrerás el mundo. Cada historia es un torrente de momentos divertidos y dramáticos, con una acción de alto octanaje y descubrimientos asombrosos, remasterizados para ser más inmersivos si cabe.'  },
  { id: 7, name: 'God of War' , description: '"God of War" es una serie de videojuegos de acción y aventura desarrollada por Santa Monica Studio y publicada por Sony Interactive Entertainment. La serie sigue las aventuras de Kratos, un antiguo guerrero espartano en su camino para vengarse de los dioses griegos que lo han traicionado.'  },
  { id: 8, name: 'Metal Slug Collection' , description: 'Metal Slug PC Collection es una recopilación de siete juegos arcade clásicos de la franquicia Metal Slug en los que se incluyen: Metal Slug, Metal Slug 2, Metal Slug 3, Metal Slug X, Metal Slug 4, Metal Slug 5 y Metal Slug 6. Cada uno de los juegos incluidos en esta compilación corrió en el hardware de NeoGeo AES, con excepción de Metal Slug 6, que se desarrolló en el hardware arcade Atomiswave.'  },
  { id: 90, name: 'Minecraft' , description: 'Minecraft, más que un simple videojuego, es todo un fenómeno social, de hecho el segundo juego más vendido de la historia por detrás de Tetris es este sandbox diseñado por Markus "Notch" Persson y desarrollado por Mojang, más tarde adquirido por Microsoft. La propuesta invita a los jugadores a sobrevivir, crear y explorar un mundo abierto generado proceduralmente, dividido en biomas y compuesto íntegramente por bloques, tanto en personajes como entorno y objetos, confiriendo una estética pixel art a su mundo en 3D.' },
  { id: 10, name: 'Medal of Honor' , description: 'El juego continúa con los hechos de Medal of Honor (2010). Algunas de los sucesos del videojuego están basados en hechos reales. Todo transcurre antes y después de un atentado suicida en Madrid, España.'},
  { id: 11, name: 'Mass Effect 2' , description: '¡De los creadores de Star Wars®: Knights of the Old Republic™, Dragon Age: Origins™, y Mass Effect™ llega la segunda y oscura entrega de la emocionante trilogía Mass EffectDos años después de que el Comandante Shepard lograse repeler a los invasores Reapers empeñados en destruir toda vida orgánica, emerge un nuevo y misterioso enemigo.'},
  { id: 12, name: 'The Last of Us' , description: 'The Last of Us Part I es un videojuego de acción y aventuras desarrollado por Naughty Dog y lanzado en 2013 para la consola PlayStation 3. La historia sigue a Joel, un hombre que vive en un mundo post-apocalíptico devastado por una pandemia que ha convertido a la mayoría de la población en seres infectados y peligrosos. Joel se une a Ellie, una adolescente valiente y decidida, para atravesar peligrosos terrenos y evitar a los infectados, así como a otros supervivientes desesperados. El juego es elogiado por su narrativa emocionalmente impactante, su jugabilidad y sus gráficos impresionantes. En 2014, se lanzó una versión remasterizada del juego para PlayStation 4.'  },
  { id: 13, name: 'Halo Infinite' , description: 'Campaña: Cuando se pierde toda esperanza y el destino de la humanidad pende de un hilo, el Jefe Maestro está listo para enfrentarse al enemigo más despiadado al que jamás haya hecho frente. Ponte la armadura del mayor héroe de la humanidad para vivir una aventura épica y explorar el descomunal anillo de Halo. Para disfrutar de la campaña, compra Halo: Infinite (campaña).'  },
  { id: 14, name: 'Bioshock Infinite' , description: 'Tercera entrega de la saga Bioshock que se ambienta en el año 1912 y presenta una experiencia narrativa totalmente nueva que saca a los jugadores del entorno familiar de Rapture, y les lanza a Columbia, una inmensa y vertiginosa ciudad en el cielo.' },
  { id: 15, name: 'Super Mario Odyssey' , description: 'Super Mario Odyssey es un juego de plataformas de aventura desarrollado y publicado por Nintendo para la consola Nintendo Switch en 2017. En este juego, Mario se embarca en un viaje para rescatar a la Princesa Peach de las garras de Bowser, quien planea casarse con ella. Mario se une a un nuevo compañero, un sombrero mágico llamado Cappy, en su viaje a través de una variedad de mundos y dimensiones.' },
  { id: 16, name: 'Fallout: New Vegas' , description: 'Recopilatorio de Fallout: New Vegas que incluye el juego original, junto a todo el contenido adicional editado. El tope de nivel también se a incrementado hasta 50... Con la introducción de la Ultimate Edition, Bethesda Softworks te ofrece una oportunidad de doble o nada para conseguir el lote completo de diversión en New Vegas. Por primera vez en un solo pack, puedes tener todo el contenido de Fallout: New Vegas incluyendo el lote completo del aclamado contenido añadido: Dead Money, Honest Hearts, Old World Blues y Lonesome Road. Para aumentar el bote, estarás armado con el más moderno alijo de armas exclusivas, tipos de munición y recetas de los packs de ampliación más recientes: Courier’s Stash y Gun Runners Arsenal. Ya seas un avezado explorador del Mojave o estés jugando por primera vez, encontrarás más amigos y enemigos que hacer, más consecuencias a tus acciones y más oportunidades para vivir en la gloria o la infamia a lo largo del Yermo. Las elecciones que hagas serán tan cruciales para tu supervivencia como siempre.' },
  { id: 17, name: 'Half-Life 2' , description: 'Grande entre los grandes para no andarnos con rodeos, Half life 2 tenía predestinado un lugar privilegiado en el hall de la gloria, del mundo de los videojuegos, ya desde su magnífica precuela. Pocas veces un título ha conseguido despertar tanta espectación, pero aún menos veces satisfacerla tan sobradamente como en esta ocasión!. No lo decimos nosotros; Hl2 es el mejor shooter de la historia, y lo saben perfectamente: Una obra maestra. Todo comienza con una visita del misterioso G-Man, alguien con pinta de funcionario del más allá, que nos despierta de un extraño letargo interdimensional. En la versión original nos dice Rise and shine, wake up and smell the ashes, despierta y huele las cenizas... Parece que Freeman ganó una batalla, pero la Tierra perdió la guerra.' },
  { id: 18, name: 'Call of duty: black ops' , description: 'Call of Duty: Black Ops será un videojuego de acción en primera persona. Desarrollado por Treyarch, anterior desarrollador del Call of Duty: World at War. El juego será el séptimo de la saga Call of Duty. Saldrá a la venta el 9 de noviembre de 2010. Sus versiones para Playstation 3 y PC serán en 3D estereoscópico. En el sistema Playstation mediante la posibilidad de reproducir Blu-ray 3D , en PC mediante NVIDIA 3D Vision y en Xbox 360 también se usara el 3d. El videojuego se desarrollará en la Guerra Fría, concretamente en la Guerra de Vietnam. El conflicto de Vietnam será el gran protagonista y culminará con el famoso asalto de la embajada iraní de Londres de 1980.' },
  { id: 19, name: 'Portal 2' , description: 'Portal 2 continúa con esa fórmula ganadora consistente en una innovadora mecánica de juego, historia y música que condujeron al Portal original a ganar más de 70 galardones y lo convirtieron en un nuevo mito de la industria.' },
];

export const PELICULAS: Hero[] = [
  { id: 20, name: 'Depredador 2', description: 'Un grupo de policías de Los Angeles se enfrenta a un misterioso asesino que descuartiza a sus víctimas con un salvajismo inusitado. Pronto, el jefe del grupo, el capitán Harrigan, descubrirá que su enemigo es un alienígena llegado a la Tierra con el único propósito de practicar la caza.' },
  { id: 21, name: 'Cars', description: 'El aspirante a campeón de carreras Rayo McQueen parece que está a punto de conseguir el éxito, la fama y todo lo que había soñado, hasta que por error toma un desvío inesperado en la polvorienta y solitaria Ruta 66. Su actitud arrogante se desvanece cuando llega a una pequeña comunidad olvidada que le enseña las cosas importantes de la vida que había olvidado.' },
  { id: 22, name: 'Ferrari', description: 'Verano de 1957. El expiloto de carreras Enzo Ferrari está en crisis. La bancarrota acecha a la empresa que él y su esposa, Laura, construyeron de la nada diez años atrás. Su tormentoso matrimonio se encuentra en medio de una gran crisis, mientras lidian con la muerte de su hijo. En esta crucial etapa, Ferrari tomará decisiones arriesgadas apostándolo todo en una única carrera que atraviesa 1.000 millas a lo largo de toda Italia: la Mille Miglia.' },
  { id: 23, name: 'Vidas pasadas', description: 'Nora y Hae Sung, dos amigos de la infancia con una fuerte conexión, se separaron cuando la familia de Nora, que entonces tenía solo 10 años, emigró desde Corea del Sur a Canadá. Muchos años después, cuando Nora trabaja como escritora de teatro en Nueva York, ambos se reencuentran, y pasarán juntos unos días que les enfrentará al amor, al destino y a las elecciones que componen una vida.' },
  { id: 24, name: 'La asesina', description: 'Maggie es una asesina drogadicta que aguarda en la cárcel el día de su ejecución. Su destino cambiará cuando un agente especializado en crímenes de Estado decide reclutarla para su equipo. Para ella sólo hay dos caminos: la muerte o convertirse en una máquina de matar al servicio del Estado. De su transformación física y moral se ocupan Bob y Amanda, que hacen de ella una joven sofisticada.' },
  { id: 25, name: 'El Padrino', description: 'La familia Corleone es una de las más poderosas de Nueva York, pero también es una de las más violentas. Don Vito Corleone es el jefe de la familia y se dedica a los negocios ilegales como el juego, la prostitución y el tráfico de drogas. Su hijo Michael, que estudia en la universidad de Dartmouth, nunca ha querido saber nada de ese mundo.' },
  { id: 26, name: 'Titanic', description: 'Jack (DiCaprio), un joven artista, gana en una partida de cartas un pasaje para viajar a América en el Titanic, el transatlántico más grande y seguro jamás construido. A bordo conoce a Rose (Kate Winslet), una joven de una buena familia venida a menos que va a contraer un matrimonio de conveniencia con Cal (Billy Zane), un millonario engreído a quien sólo interesa el prestigioso apellido de su prometida.' },
  { id: 27, name: 'Jurassic Park', description: 'En una isla remota, un rico magnate lleva a cabo un espectacular y controvertido experimento científico: clonar dinosaurios extinguidos hace eones. Contratando los mejores científicos, su avanzada ingeniería genética consigue devolver a la vida varias especies de dinosaurios. Pero el proyecto se descontrola cuando los poderosos depredadores escapan.' },
  { id: 28, name: 'Harry Potter y la Piedra Filosofal', description: 'Harry Potter es un niño huérfano criado por sus abominables tíos. El día de su undécimo cumpleaños, Harry recibe la inesperada visita de un hombre gigantesco llamado Rubeus Hagrid. Este le revela que su padre era un mago y que su madre era una bruja, y que él también posee poderes mágicos.' },
  { id: 29, name: 'Matrix', description: 'Un pirata informático llamado Neo descubre que el mundo en el que vive es una simulación controlada por inteligencias artificiales. Liberado de la Matrix por Morfeo, líder de un grupo de rebeldes que luchan contra la opresión de las máquinas, Neo se unirá a ellos en su lucha contra el sistema, convirtiéndose en su mayor esperanza de liberación.' }
];
